set(_CATKIN_CURRENT_PACKAGE "laser_scanner_eric")
set(laser_scanner_eric_MAINTAINER "ed <ed@todo.todo>")
set(laser_scanner_eric_DEPRECATED "")
set(laser_scanner_eric_VERSION "0.0.0")
set(laser_scanner_eric_BUILD_DEPENDS "roscpp" "std_msgs" "sensor_msgs" "nav_msgs" "geometry_msgs" "message_generation" "tf")
set(laser_scanner_eric_RUN_DEPENDS "tf" "message_runtime" "sensor_msgs" "geometry_msgs" "nav_msgs" "roscpp" "std_msgs")
set(laser_scanner_eric_BUILDTOOL_DEPENDS "catkin")